export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
